Create message engine core
KuzniaCo/Haris pull request #10
Opened 2017-03-15 18:35 UTC by sebcza

2017-03-15 18:56 UTC, pacewicz requested changes

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/AppCoreBootstrapper.cs
> +            Container.RegisterSingleton<ICubeRepository, CubeRepository>();
formatowanie

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +        public TempCube(IEventAggregator eventAggregator, Cube cubeEntity, CubeRepository cubeRepository)
`TemperatureCube` (znaczące nazwy)

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +            messageItems = message.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries);
hint: `RemoveEmptyEntries` może szkodzić, jeśli rzeczywiście pojawi się coś pustego

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +                _cubeEntity.Logs = new List<Log>();
to chyba odpowiedzialność samego obiektu `Cube`

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +        public void OnReceivedTemp(string value, string message)
`OnTemperatureReceived`

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +                Date = DateTime.Now,
hm, nie mamy abstrakcji na czas? (`SystemTime` - przydatne do testów)

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +            _eventAggregator.Publish(new AttributedMessageEvent(_cubeEntity + "|" + TempCubeActions.SET_INTERVAL + "|"));
przydałby się serwis do tworzenia tych stringów

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Cubes/TempCube.cs
> +        public enum TempCubeActions
do osobnego pliku (+poprawny namespace)

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Modules/Endpoint/EndpointModule.cs
> +
zbędne

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Modules/MessageEngine/MessageEngineModule.cs
> +            String[] messageItems = message.Split(new char[] { '|' }, StringSplitOptions.RemoveEmptyEntries);
serwis do parsowania?

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Modules/MessageEngine/MessageEngineModule.cs
> +                Logger.LogError("Not found cube addressed: " + address);
`$"Cube at {address} not found"`

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.Core/Modules/MessageEngine/MessageEngineModule.cs
> +            var cubeType = GetType().Assembly.GetTypes()
przydałby się serwis do tego (64-68); formatowanie (`x=>x` => `x => x`)

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/DataModels/Cube.cs
> +        public string Name { get; set; }
hint: brakuje atrybutu bsona - nie wiem, czy zamierzone

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/Haris.DataModel.csproj
> +    <Compile Include="Repositories\MongoRepository.cs" />
folder/namespace implementacji

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/Repositories/Implementation/CubeRepository.cs
> +            _cubes = _db.GetCollection<Cube>("cubes");
hint: może by się dało zastąpić stringi `nameof`em

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/Repositories/Implementation/CubeRepository.cs
> +            return _cubes.FindSync(x => x.CubeAddress.Contains(address)).FirstOrDefault();
sugerowałbym wrzucenie asynchronicznych dostępów

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/Repositories/Implementation/CubeRepository.cs
> +            _cubes.ReplaceOne(x=>x.Id == cube.Id, cube);
formatowanie

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.DataModel/Repositories/MongoRepository.cs
> +    public abstract class MongoRepository
coś o bazowości w nazwie

2017-03-15 18:56 UTC, pacewicz commented on core/Haris.HostApp/app.config
> +    <add name="db" connectionString="mongodb://localhost:27017/CubeServer"/>
przydałby się skrypt na łatwe stawianie tego

2017-03-15 19:37 UTC, sebcza commented on core/Haris.HostApp/app.config
> +    <add name="db" connectionString="mongodb://localhost:27017/CubeServer"/>
Myślałem, żeby dodać biny mongo do solucji i spróbować to postawić jako moduł. Co o tym myślisz ?

2017-03-15 20:28 UTC, pacewicz commented on core/Haris.HostApp/app.config
> +    <add name="db" connectionString="mongodb://localhost:27017/CubeServer"/>
Do LFS można dodać - tylko wtedy serwis do odpalania i chciałbym trzymać cross-platformowość (raspbian+windows)

2017-03-16 11:18 UTC, sebcza commented on core/Haris.Core/Cubes/TempCube.cs
> +                _cubeEntity.Logs = new List<Log>();
Nie do końca. Chciałbym aby każdy typ cuba mógł logować  na swój sposób.

2017-03-16 11:21 UTC, sebcza commented on core/Haris.Core/Modules/Endpoint/EndpointModule.cs
> +
Nie jest zbędne. Pokaże CI jak to się zachowuje bez tego.

2017-03-16 11:23 UTC, sebcza commented on core/Haris.DataModel/Repositories/Implementation/CubeRepository.cs
> +            return _cubes.FindSync(x => x.CubeAddress.Contains(address)).FirstOrDefault();
zgadzam się

2017-03-20 22:33 UTC, merged